name: GitHub Actions - Merge to master
run-name: ${{ github.actor }} is running this action
on:
  push:
    branches:
      - "*"
jobs:
  Auto-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout origin/master
          git pull
          git merge ${{ github.ref_name }}
