name: GitHub Actions - Merge to master
run-name: ${{ github.actor }} is running this action
on:
  push:
    branches:
      - "RN-*"
jobs:
  Auto-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> staging
        uses: ${{ github.repository }}
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
